disabled_rules:
  - force_cast
  - force_try
  - variable_name_min_length
  - function_body_length
  - line_length
  - file_length
included:
  - Shine
excluded:
  - Carthage
  - Pods
type_body_length:
  - 1000 # warning
  - 1200 # error
variable_name_max_length:
  - 40 # warning
  - 60 # error
