disabled_rules:
  - force_cast
  - force_try
  - variable_name
  - function_body_length
  - line_length
  - file_length
  - cyclomatic_complexity
included:
  - Shine
excluded:
  - Carthage
  - Pods
type_body_length:
  - 1000 # warning
  - 1200 # error
